[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ignored_error_codes = [3420,3628,2072,2018,6321,5667,3860,5574,1878,2519,9302]
remappings = [
  "@perimetersec/fuzzlib=lib/fuzzlib",
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
]


# "@openzeppelin/contracts": "4.4.2",